
init:
   - git config --global core.autocrlf true

environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "7"

install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off

